# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15b85a36c21bb722cef976bd7632fd78e17411e42749d25be942052a9737c7826d981d118c96c524ce880df945213b6b26e0d89d37858dff706d5065fe9e1e24

test:
  secret_key_base: a24d7babfa216960192a9b58cf456491587090cf560c4dbd6ec620a7e3224b0371e2cf1acc0a5099cb2a6e78a16db4832c238766392c08c75eb77558b4e51d6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
